config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'contents#index'
  resources :contents, only: [:index, :show, :destroy, :new, :create, :update, :edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  validates :title, presence: true
  validates :status, presence: true
  validates :source, presence: true
  validates :itinerary, presence: true
  validates :country, presence: true

  include PgSearch
  pg_search_scope :search_for_content,
    against: [ :title, :country, :destination, :activity, :source, :status, :length, :style, :provider, :code, :start_finish ],
    using: {
      tsearch: { prefix: true }
    }

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    if params[:query].present?
      contents = policy_scope(Content).order(updated_at: :desc)
      @contents = Content.search_for_content(params[:query]).paginate(page:params[:page], per_page: 20).order(updated_at: :desc)
    else
      @contents = Content.paginate(page:params[:page], per_page: 20).order(updated_at: :desc)
    end
  end

  def show
    @content = Content.friendly.find(params[:id])
    authorize @content
  end

  def new

    @content = Content.new
    authorize @content
  end

  def create
    @content = Content.new(content_params)
    authorize @content
      if @content.save
        redirect_to content_path(@content)
      else
        render :new
      end
  end

  def edit
    @content = Content.friendly.find(params[:id])
    authorize @content
  end

  def update
    @content = Content.friendly.find(params[:id])
    authorize @content
    if  current_user.editor? && @content.status == "editing" ||
        current_user.proofread? && @content.status == "Proofreading" || current_user.admin?
      @content.update(content_params)
      redirect_to content_path(@content)
    else
      redirect_to content_path(@content)
      flash[:alert] = "You don't have permission to edit"
    end
  end

  def destroy
    @content = Content.friendly.find(params[:id])
    authorize @content
    @content.destroy
    if @content.destroy
      flash[:notice] = "\"#{@content.title}\" was successfully deleted."
      redirect_to contents_path
    else
      flash[:alert] = "There was an error deleting the content."
      render :show
    end
  end
  private

    def content_params
      params.require(:content).permit(:title, :new_title,
        :source, :status, :root, :photo,
        :itinerary, :summary, :highlight, :go_next,
        :country, :destination, :activity1, :activity2, :length, :note,
        :code, :provider, :start_finish, :style, :them,
        :comfort, :related_trips
        )

    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contents/_form.html.erb
<%= simple_form_for @content do |f| %>
<% if @content.errors.any? %>
<div class="errors-container">
  <ul>
    <% @content.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.input :title, label:'title',:placeholder => 'Name', class: 'form-control'%>
</div>
<div class="form-group">
  <%= f.input :new_title, label:'new title',label_html: { class: 'note' },:placeholder => 'Sexy title that sale', class: 'form-control'%>
</div>
<div class="form-row">
  <div class="form-group col-md-4">
    <%= f.input :country, label:'country',as: :select, :collection => ["Bhutan","Cambodia","China", "Laos", "Nepal", "Myanmar", "Malaysia", "Mongolia", "Thailand", "Vietnam", "Indonesia", "India","Philippines", "Sri Lanka", "Japan", "Kyrgyzstan", "Uzbekistan", "Azerbaijan" ], class: 'form-control'%>
  </div>
  <div class="form-group col-md-4">
    <%= f.input :activity1, label:'activity 1', as: :select,:collection => ["Biking","Hiking" ,"Rafting","Unesco other", "Other Water","Outdoor","Summary", "Visa", "Weather", "Festival", "Q&A"], class: 'form-control'%>
  </div>
  <div class="form-group col-md-4">
    <%= f.input :activity2, label:'activity 2', as: :select,:collection => ["Biking","Hiking" ,"Rafting","Unesco other", "Other Water","Outdoor","Summary", "Visa", "Weather", "Festival", "Q&A"], class: 'form-control'%>
  </div>
</div>
<div class="form-row">
  <div class="form-group col-md-4">
    <%= f.input :destination, label:'location', :placeholder => 'Chiangmai, Sapa, Luang Pra Phang', class: 'form-control'%>
  </div>
  <div class="form-group col-md-4">
    <%= f.input :source, label:'source', :placeholder => 'John 2008', class: 'form-control'%>
  </div>
  
  <div class="form-group col-md-4">
    <%= f.input :status, label:'status', as: :select, :collection => ["editing", "Proofreading" ,"Approving","Publish"], selected: "editing", class: 'form-control'%>
  </div>


</div>
<div class="form-group">
  <%= f.input :summary, label: 'Summary',label_html: { class: 'note' }, :as => :trix_editor, :input_html => {:rows => 10}, class: "form-control note" %>
</div>
<div class="form-group">
  <%= f.input :highlight, label: 'Highlight', label_html: { class: 'note' },:as => :trix_editor, :input_html => {:rows => 5}, class: "form-control note" %>
</div>
<div class="form-group">
  <%= f.input :itinerary, label: 'Itinerary', :as => :trix_editor, :input_html => {:rows => 12}, class: "form-control" %>
</div>
<div class="form-row">
  <div class="form-group col-md-4">
    <%= f.input :code, label:'code',class: 'form-control'%>
  </div>
  <div class="form-group col-md-4">
    <%= f.input :provider, label:'Provider', class: 'form-control'%>
  </div>
  <div class="form-group col-md-4">
    <%= f.input :length, label:'duration', :placeholder => '4 days | 3 night', class: 'form-control'%>
  </div>
</div>
<div class="form-row">
  <div class="form-group col-md-4">
    <%= f.input :style, label:'style',class: 'form-control'%>
  </div>
  <div class="form-group col-md-4">
    <%= f.input :theme, label:'theme', class: 'form-control'%>
  </div>
  <div class="form-group col-md-4">
    <%= f.input :comfort, label:'comfort', class: 'form-control'%>
  </div>
</div>
<div class="form-row">
  <div class="form-group col-md-4">
    <%= f.input :start_finish, label:'start/finish destination', :placeholder => 'Chiangmai-Hanoi', class: 'form-control'%>
  </div>
  <div class="form-group col-md-4">
    <%= f.input :related_trips, label:'Related trips', class: 'form-control'%>
  </div>
  <div class="form-group col-md-4">
    <%= f.input :go_next, label:'Where go next', class: 'form-control'%>
  </div>
</div>
<div class="form-group">
  <%= f.input :note, label:'Internal note', :placeholder => 'note for writer, developer, admin', class: 'form-control'%>
</div>
<%= f.submit class: 'btn btn-info mb-5' %>
<%= f.button :button, 'Cancel', type: :reset, class: 'btn btn-outline-info mb-5' %>

<%end%>

app/views/contents/edit.html.erb
<div class="container">
  <h2 class="mt-3">Edit '<%= @content.title %>'</h2>
  <%= render 'form', content: @content %>
</div>

app/views/contents/index.html.erb
<div class="container">
  <div class="mt-3">
      <%= simple_form_for :search, url: contents_path, method: :get do %>
    <div class="search-form-control form-group">
      <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "type in : thailand, approved, hiking ect.."
    %>
      <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
      </button>
    </div>
  <% end %>
  </div>
  <div>
    <%= will_paginate(@things, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

  </div>
  <div class="row">
    <% @contents.each do |content| %>
    <%= link_to content_path(content), class:"content-card", :action => 'go' do %>
  <div class="card m-3">
    <div class="card-header">
      Note: <%= content.note.first(25) %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= content.title.first(20) %></h5>
      <p class="card-text"><strong>Root: </strong><%= content.country %> | <%= content.destination %> | <%= content.activity1 %></p>
      <p class="card-text"><strong>Updated: </strong><%= content.updated_at.strftime('%b %d %Y') %></p>
      <p ><strong>status:</strong> <%= content.status %></p>
    </div>

  </div>
  <%end%>
    <% end %>
  </div>
  <div>
    <%= will_paginate(@things, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

  </div>
</div>

app/views/contents/new.html.erb
<div class="container">
  <h2 class="mt-3">Add New Tour Content</h2>
  <%= render 'form', tour: @content %>
</div>

app/views/contents/show.html.erb
<div class="container my-5">
  <div class="wrapper">
    <div class="content-col col-md-8 col-12">
      <h3 class="content-title"><% if @content.new_title.present?%>
        <%= @content.new_title %>
          <% else %>
          <%= @content.title %>
          <% end %>
        </h3>
      <p><strong>Root: </strong><%= @content.country %> | <%= @content.destination %> | <%= @content.activity1 %></p>
      <p><strong>Source: </strong><%= @content.source %></p>
      <div class="content-tabs">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="original-tab" data-toggle="tab" href="#original" role="tab" aria-controls="original" aria-selected="true">Summary & Highlight</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="modifi-tab" data-toggle="tab" href="#modifi" role="tab" aria-controls="profile" aria-selected="false">Itinerary</a>
          </li>
        </ul>
        <div class="tab-content mt-4" id="myTabContent">
          <div class="tab-pane fade show active" id="original" role="tabpanel" aria-labelledby="original-tab">
            <% if @content.summary.present? || @content.highlight.present? %>
            <p><strong>Summary:</strong> <%= @content.summary.html_safe %></p> <br />
            <p><strong>Highlight:</strong> <%= @content.highlight.html_safe %></p>
            <% else %>
            <p>Please add content</p>
            <% end %></div>
          <div class="tab-pane fade" id="modifi" role="tabpanel" aria-labelledby="profile-tab"><p><%= @content.itinerary.html_safe %></p></div>
        </div>
      </div>
    </div>
    <div class="info-col col-md-4 col-12 ml-2">
      <p class="content-status col-12"><%= @content.status %></p>
      <div class="d-flex justify-content-around py-2">
      <% if policy(@content).destroy? %>
      <%= link_to 'Delete', @content_path, class: "btn btn-outline-danger col-4", method: "delete", data: { confirm: "Are you sure you want to delete '#{@content.title}'?" } %>
      <% end %>

      <% if current_user.editor? && @content.status == "editing" ||
        current_user.proofread? && @content.status == "Proofreading" || current_user.admin? %>
      <%= link_to 'Edit', edit_content_path, class: "btn btn-outline-warning col-4" %>
      <% end %>

      </div>
      <div class="flash flash-warning alert alert-dismissible fade  show" role="alert">
      <span>Note: <%= @content.note %></span>
      </div>
      <div class="mt-5">
        <p><strong>Updated: <%= @content.updated_at.strftime('%b %d %Y') %></strong></p>
        <p><span>Code: </span><%= @content.code %></p>
        <p><span>Provider: </span><%= @content.provider %></p>
        <p><span>Start/Finish: </span><%= @content.start_finish %></p>
        <p><span>Style: </span><%= @content.style %></p>
        <p><span>Theme: </span><%= @content.theme %></p>
        <p><span>Comfort: </span><%= @content.comfort %></p>
        <p><span>Related Trips: </span><%= @content.related_trips %></p>
        <p><span>Duration: </span><%= @content.length %></p>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="trix.css">
    <script type="text/javascript" src="trix.js"></script>
    <title>AA Tour Contents</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <%= link_to "www.itrekasia.com", class: "navbar-brand" do %>
      <%= image_tag "logo-small.png", style: 'width: 70px; height: 35px' %>
      <% end %>
    </li>
  </ul>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item m-2">
      <%= link_to "All Contents", contents_path, class: "btn btn-outline-secondary" %>
    </li>
    <% if current_user.admin? || current_user.vt? %>
    <li class="nav-item m-2">
      <%= link_to "Add New Content", new_content_path, class: "btn btn-outline-secondary" %>
    </li>
    <% end %>
    <li class="nav-item active m-2">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-outline-info" %>
        </li>
      <li>
          <%if current_user.admin?%>
            <p class="m-3">Welcome Admin</p>
          <%else%>
            <p class="m-3"> Welcome <%= current_user.email.first(5)%></p>
          <%end%>
        </li>


      <% else %>
        <li class="nav-item hide">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>